
CREATE TABLE `countries` (
  `id` int NOT NULL AUTO_INCREMENT,
`country_code` varchar(2) NOT NULL default '',
`name_en` varchar(100) NOT NULL default '',
`name_ar` varchar(100) NOT NULL default '',
`nationality_en` varchar(100) NOT NULL default '',
`nationality_ar` varchar(100) NOT NULL default '',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 
-- Dumping data for table `countries`
-- 
INSERT INTO `countries` VALUES (null,'AF', 'Afghanistan','أفغانستان','Afghan','أفغانستاني');
INSERT INTO `countries` VALUES (null,'AL', 'Albania','ألبانيا','Albanian','ألباني');
INSERT INTO `countries` VALUES (null,'AX', 'Aland Islands','جزر آلاند','Aland Islander','آلاندي');
INSERT INTO `countries` VALUES (null,'DZ', 'Algeria','الجزائر','Algerian','جزائري');
INSERT INTO `countries` VALUES (null,'AS', 'American Samoa','ساموا-الأمريكي','American Samoan','أمريكي سامواني');
INSERT INTO `countries` VALUES (null,'AD', 'Andorra','أندورا','Andorran','أندوري');
INSERT INTO `countries` VALUES (null,'AO', 'Angola','أنغولا','Angolan','أنقولي');
INSERT INTO `countries` VALUES (null,'AI', 'Anguilla','أنغويلا','Anguillan','أنغويلي');
INSERT INTO `countries` VALUES (null,'AQ', 'Antarctica','أنتاركتيكا','Antarctican','أنتاركتيكي');
INSERT INTO `countries` VALUES (null,'AG', 'Antigua and Barbuda','أنتيغوا وبربودا','Antiguan','بربودي');
INSERT INTO `countries` VALUES (null,'AR', 'Argentina','الأرجنتين','Argentinian','أرجنتيني');
INSERT INTO `countries` VALUES (null,'AM', 'Armenia','أرمينيا','Armenian','أرميني');
INSERT INTO `countries` VALUES (null,'AW', 'Aruba','أروبه','Aruban','أوروبهيني');
INSERT INTO `countries` VALUES (null,'AU', 'Australia','أستراليا','Australian','أسترالي');
INSERT INTO `countries` VALUES (null,'AT', 'Austria','النمسا','Austrian','نمساوي');
INSERT INTO `countries` VALUES (null,'AZ', 'Azerbaijan','أذربيجان','Azerbaijani','أذربيجاني');
INSERT INTO `countries` VALUES (null,'BS', 'Bahamas','الباهاماس','Bahamian','باهاميسي');
INSERT INTO `countries` VALUES (null,'BH', 'Bahrain','البحرين','Bahraini','بحريني');
INSERT INTO `countries` VALUES (null,'BD', 'Bangladesh','بنغلاديش','Bangladeshi','بنغلاديشي');
INSERT INTO `countries` VALUES (null,'BB', 'Barbados','بربادوس','Barbadian','بربادوسي');
INSERT INTO `countries` VALUES (null,'BY', 'Belarus','روسيا البيضاء','Belarusian','روسي');
INSERT INTO `countries` VALUES (null,'BE', 'Belgium','بلجيكا','Belgian','بلجيكي');
INSERT INTO `countries` VALUES (null,'BZ', 'Belize','بيليز','Belizean','بيليزي');
INSERT INTO `countries` VALUES (null,'BJ', 'Benin','بنين','Beninese','بنيني');
INSERT INTO `countries` VALUES (null,'BL', 'Saint Barthelemy','سان بارتيلمي','Saint Barthelmian','سان بارتيلمي');
INSERT INTO `countries` VALUES (null,'BM', 'Bermuda','جزر برمودا','Bermudan','برمودي');
INSERT INTO `countries` VALUES (null,'BT', 'Bhutan','بوتان','Bhutanese','بوتاني');
INSERT INTO `countries` VALUES (null,'BO', 'Bolivia','بوليفيا','Bolivian','بوليفي');
INSERT INTO `countries` VALUES (null,'BA', 'Bosnia and Herzegovina','البوسنة و الهرسك','Bosnian / Herzegovinian','بوسني/هرسكي');
INSERT INTO `countries` VALUES (null,'BW', 'Botswana','بوتسوانا','Botswanan','بوتسواني');
INSERT INTO `countries` VALUES (null,'BV', 'Bouvet Island','جزيرة بوفيه','Bouvetian','بوفيهي');
INSERT INTO `countries` VALUES (null,'BR', 'Brazil','البرازيل','Brazilian','برازيلي');
INSERT INTO `countries` VALUES (null,'IO', 'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني','British Indian Ocean Territory','إقليم المحيط الهندي البريطاني');
INSERT INTO `countries` VALUES (null,'BN', 'Brunei Darussalam','بروني','Bruneian','بروني');
INSERT INTO `countries` VALUES (null,'BG', 'Bulgaria','بلغاريا','Bulgarian','بلغاري');
INSERT INTO `countries` VALUES (null,'BF', 'Burkina Faso','بوركينا فاسو','Burkinabe','بوركيني');
INSERT INTO `countries` VALUES (null,'BI', 'Burundi','بوروندي','Burundian','بورونيدي');
INSERT INTO `countries` VALUES (null,'KH', 'Cambodia','كمبوديا','Cambodian','كمبودي');
INSERT INTO `countries` VALUES (null,'CM', 'Cameroon','كاميرون','Cameroonian','كاميروني');
INSERT INTO `countries` VALUES (null,'CA', 'Canada','كندا','Canadian','كندي');
INSERT INTO `countries` VALUES (null,'CV', 'Cape Verde','الرأس الأخضر','Cape Verdean','الرأس الأخضر');
INSERT INTO `countries` VALUES (null,'KY', 'Cayman Islands','جزر كايمان','Caymanian','كايماني');
INSERT INTO `countries` VALUES (null,'CF', 'Central African Republic','جمهورية أفريقيا الوسطى','Central African','أفريقي');
INSERT INTO `countries` VALUES (null,'TD', 'Chad','تشاد','Chadian','تشادي');
INSERT INTO `countries` VALUES (null,'CL', 'Chile','شيلي','Chilean','شيلي');
INSERT INTO `countries` VALUES (null,'CN', 'China','الصين','Chinese','صيني');
INSERT INTO `countries` VALUES (null,'CX', 'Christmas Island','جزيرة عيد الميلاد','Christmas Islander','جزيرة عيد الميلاد');
INSERT INTO `countries` VALUES (null,'CC', 'Cocos (Keeling) Islands','جزر كوكوس','Cocos Islander','جزر كوكوس');
INSERT INTO `countries` VALUES (null,'CO', 'Colombia','كولومبيا','Colombian','كولومبي');
INSERT INTO `countries` VALUES (null,'KM', 'Comoros','جزر القمر','Comorian','جزر القمر');
INSERT INTO `countries` VALUES (null,'CG', 'Congo','الكونغو','Congolese','كونغي');
INSERT INTO `countries` VALUES (null,'CK', 'Cook Islands','جزر كوك','Cook Islander','جزر كوك');
INSERT INTO `countries` VALUES (null,'CR', 'Costa Rica','كوستاريكا','Costa Rican','كوستاريكي');
INSERT INTO `countries` VALUES (null,'HR', 'Croatia','كرواتيا','Croatian','كوراتي');
INSERT INTO `countries` VALUES (null,'CU', 'Cuba','كوبا','Cuban','كوبي');
INSERT INTO `countries` VALUES (null,'CY', 'Cyprus','قبرص','Cypriot','قبرصي');
INSERT INTO `countries` VALUES (null,'CW', 'Curaçao','كوراساو','Curacian','كوراساوي');
INSERT INTO `countries` VALUES (null,'CZ', 'Czech Republic','الجمهورية التشيكية','Czech','تشيكي');
INSERT INTO `countries` VALUES (null,'DK', 'Denmark','الدانمارك','Danish','دنماركي');
INSERT INTO `countries` VALUES (null,'DJ', 'Djibouti','جيبوتي','Djiboutian','جيبوتي');
INSERT INTO `countries` VALUES (null,'DM', 'Dominica','دومينيكا','Dominican','دومينيكي');
INSERT INTO `countries` VALUES (null,'DO', 'Dominican Republic','الجمهورية الدومينيكية','Dominican','دومينيكي');
INSERT INTO `countries` VALUES (null,'EC', 'Ecuador','إكوادور','Ecuadorian','إكوادوري');
INSERT INTO `countries` VALUES (null,'EG', 'Egypt','مصر','Egyptian','مصري');
INSERT INTO `countries` VALUES (null,'SV', 'El Salvador','إلسلفادور','Salvadoran','سلفادوري');
INSERT INTO `countries` VALUES (null,'GQ', 'Equatorial Guinea','غينيا الاستوائي','Equatorial Guinean','غيني');
INSERT INTO `countries` VALUES (null,'ER', 'Eritrea','إريتريا','Eritrean','إريتيري');
INSERT INTO `countries` VALUES (null,'EE', 'Estonia','استونيا','Estonian','استوني');
INSERT INTO `countries` VALUES (null,'ET', 'Ethiopia','أثيوبيا','Ethiopian','أثيوبي');
INSERT INTO `countries` VALUES (null,'FK', 'Falkland Islands (Malvinas)','جزر فوكلاند','Falkland Islander','فوكلاندي');
INSERT INTO `countries` VALUES (null,'FO', 'Faroe Islands','جزر فارو','Faroese','جزر فارو');
INSERT INTO `countries` VALUES (null,'FJ', 'Fiji','فيجي','Fijian','فيجي');
INSERT INTO `countries` VALUES (null,'FI', 'Finland','فنلندا','Finnish','فنلندي');
INSERT INTO `countries` VALUES (null,'FR', 'France','فرنسا','French','فرنسي');
INSERT INTO `countries` VALUES (null,'GF', 'French Guiana','غويانا الفرنسية','French Guianese','غويانا الفرنسية');
INSERT INTO `countries` VALUES (null,'PF', 'French Polynesia','بولينيزيا الفرنسية','French Polynesian','بولينيزيي');
INSERT INTO `countries` VALUES (null,'TF', 'French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية','French','أراض فرنسية جنوبية وأنتارتيكية');
INSERT INTO `countries` VALUES (null,'GA', 'Gabon','الغابون','Gabonese','غابوني');
INSERT INTO `countries` VALUES (null,'GM', 'Gambia','غامبيا','Gambian','غامبي');
INSERT INTO `countries` VALUES (null,'GE', 'Georgia','جيورجيا','Georgian','جيورجي');
INSERT INTO `countries` VALUES (null,'DE', 'Germany','ألمانيا','German','ألماني');
INSERT INTO `countries` VALUES (null,'GH', 'Ghana','غانا','Ghanaian','غاني');
INSERT INTO `countries` VALUES (null,'GI', 'Gibraltar','جبل طارق','Gibraltar','جبل طارق');
INSERT INTO `countries` VALUES (null,'GG', 'Guernsey','غيرنزي','Guernsian','غيرنزي');
INSERT INTO `countries` VALUES (null,'GR', 'Greece','اليونان','Greek','يوناني');
INSERT INTO `countries` VALUES (null,'GL', 'Greenland','جرينلاند','Greenlandic','جرينلاندي');
INSERT INTO `countries` VALUES (null,'GD', 'Grenada','غرينادا','Grenadian','غرينادي');
INSERT INTO `countries` VALUES (null,'GP', 'Guadeloupe','جزر جوادلوب','Guadeloupe','جزر جوادلوب');
INSERT INTO `countries` VALUES (null,'GU', 'Guam','جوام','Guamanian','جوامي');
INSERT INTO `countries` VALUES (null,'GT', 'Guatemala','غواتيمال','Guatemalan','غواتيمالي');
INSERT INTO `countries` VALUES (null,'GN', 'Guinea','غينيا','Guinean','غيني');
INSERT INTO `countries` VALUES (null,'GW', 'Guinea-Bissau','غينيا-بيساو','Guinea-Bissauan','غيني');
INSERT INTO `countries` VALUES (null,'GY', 'Guyana','غيانا','Guyanese','غياني');
INSERT INTO `countries` VALUES (null,'HT', 'Haiti','هايتي','Haitian','هايتي');
INSERT INTO `countries` VALUES (null,'HM', 'Heard and Mc Donald Islands','جزيرة هيرد وجزر ماكدونالد','Heard and Mc Donald Islanders','جزيرة هيرد وجزر ماكدونالد');
INSERT INTO `countries` VALUES (null,'HN', 'Honduras','هندوراس','Honduran','هندوراسي');
INSERT INTO `countries` VALUES (null,'HK', 'Hong Kong','هونغ كونغ','Hongkongese','هونغ كونغي');
INSERT INTO `countries` VALUES (null,'HU', 'Hungary','المجر','Hungarian','مجري');
INSERT INTO `countries` VALUES (null,'IS', 'Iceland','آيسلندا','Icelandic','آيسلندي');
INSERT INTO `countries` VALUES (null,'IN', 'India','الهند','Indian','هندي');
INSERT INTO `countries` VALUES (null,'ID', 'Indonesia','أندونيسيا','Indonesian','أندونيسيي');
INSERT INTO `countries` VALUES (null,'IR', 'Iran','إيران','Iranian','إيراني');
INSERT INTO `countries` VALUES (null,'IQ', 'Iraq','العراق','Iraqi','عراقي');
INSERT INTO `countries` VALUES (null,'IE', 'Ireland','إيرلندا','Irish','إيرلندي');
INSERT INTO `countries` VALUES (null,'IL', 'Israel','إسرائيل','Israeli','إسرائيلي');
INSERT INTO `countries` VALUES (null,'IT', 'Italy','إيطاليا','Italian','إيطالي');
INSERT INTO `countries` VALUES (null,'CI', 'Ivory Coast','ساحل العاج','Ivory Coastian','ساحل العاج');
INSERT INTO `countries` VALUES (null,'JE', 'Jersey','جيرزي','Jersian','جيرزي');
INSERT INTO `countries` VALUES (null,'JM', 'Jamaica','جمايكا','Jamaican','جمايكي');
INSERT INTO `countries` VALUES (null,'JP', 'Japan','اليابان','Japanese','ياباني');
INSERT INTO `countries` VALUES (null,'JO', 'Jordan','الأردن','Jordanian','أردني');
INSERT INTO `countries` VALUES (null,'KZ', 'Kazakhstan','كازاخستان','Kazakh','كازاخستاني');
INSERT INTO `countries` VALUES (null,'KE', 'Kenya','كينيا','Kenyan','كيني');
INSERT INTO `countries` VALUES (null,'KI', 'Kiribati','كيريباتي','I-Kiribati','كيريباتي');
INSERT INTO `countries` VALUES (null,'KP', 'Korea(North Korea)','كوريا الشمالية','North Korean','كوري');
INSERT INTO `countries` VALUES (null,'KR', 'Korea(South Korea)','كوريا الجنوبية','South Korean','كوري');
INSERT INTO `countries` VALUES (null,'XK', 'Kosovo','كوسوفو','Kosovar','كوسيفي');
INSERT INTO `countries` VALUES (null,'KW', 'Kuwait','الكويت','Kuwaiti','كويتي');
INSERT INTO `countries` VALUES (null,'KG', 'Kyrgyzstan','قيرغيزستان','Kyrgyzstani','قيرغيزستاني');
INSERT INTO `countries` VALUES (null,'LA', 'Lao PDR','لاوس','Laotian','لاوسي');
INSERT INTO `countries` VALUES (null,'LV', 'Latvia','لاتفيا','Latvian','لاتيفي');
INSERT INTO `countries` VALUES (null,'LB', 'Lebanon','لبنان','Lebanese','لبناني');
INSERT INTO `countries` VALUES (null,'LS', 'Lesotho','ليسوتو','Basotho','ليوسيتي');
INSERT INTO `countries` VALUES (null,'LR', 'Liberia','ليبيريا','Liberian','ليبيري');
INSERT INTO `countries` VALUES (null,'LY', 'Libya','ليبيا','Libyan','ليبي');
INSERT INTO `countries` VALUES (null,'LT', 'Lithuania','لتوانيا','Lithuanian','لتوانيي');
INSERT INTO `countries` VALUES (null,'LU', 'Luxembourg','لوكسمبورغ','Luxembourger','لوكسمبورغي');
INSERT INTO `countries` VALUES (null,'LK', 'Sri Lanka','سريلانكا','Sri Lankian','سريلانكي');
INSERT INTO `countries` VALUES (null,'MO', 'Macau','ماكاو','Macanese','ماكاوي');
INSERT INTO `countries` VALUES (null,'MK', 'Macedonia','مقدونيا','Macedonian','مقدوني');
INSERT INTO `countries` VALUES (null,'MG', 'Madagascar','مدغشقر','Malagasy','مدغشقري');
INSERT INTO `countries` VALUES (null,'MW', 'Malawi','مالاوي','Malawian','مالاوي');
INSERT INTO `countries` VALUES (null,'MY', 'Malaysia','ماليزيا','Malaysian','ماليزي');
INSERT INTO `countries` VALUES (null,'MV', 'Maldives','المالديف','Maldivian','مالديفي');
INSERT INTO `countries` VALUES (null,'ML', 'Mali','مالي','Malian','مالي');
INSERT INTO `countries` VALUES (null,'MT', 'Malta','مالطا','Maltese','مالطي');
INSERT INTO `countries` VALUES (null,'MH', 'Marshall Islands','جزر مارشال','Marshallese','مارشالي');
INSERT INTO `countries` VALUES (null,'MQ', 'Martinique','مارتينيك','Martiniquais','مارتينيكي');
INSERT INTO `countries` VALUES (null,'MR', 'Mauritania','موريتانيا','Mauritanian','موريتانيي');
INSERT INTO `countries` VALUES (null,'MU', 'Mauritius','موريشيوس','Mauritian','موريشيوسي');
INSERT INTO `countries` VALUES (null,'YT', 'Mayotte','مايوت','Mahoran','مايوتي');
INSERT INTO `countries` VALUES (null,'MX', 'Mexico','المكسيك','Mexican','مكسيكي');
INSERT INTO `countries` VALUES (null,'FM', 'Micronesia','مايكرونيزيا','Micronesian','مايكرونيزيي');
INSERT INTO `countries` VALUES (null,'MD', 'Moldova','مولدافيا','Moldovan','مولديفي');
INSERT INTO `countries` VALUES (null,'MC', 'Monaco','موناكو','Monacan','مونيكي');
INSERT INTO `countries` VALUES (null,'MN', 'Mongolia','منغوليا','Mongolian','منغولي');
INSERT INTO `countries` VALUES (null,'ME', 'Montenegro','الجبل الأسود','Montenegrin','الجبل الأسود');
INSERT INTO `countries` VALUES (null,'MS', 'Montserrat','مونتسيرات','Montserratian','مونتسيراتي');
INSERT INTO `countries` VALUES (null,'MA', 'Morocco','المغرب','Moroccan','مغربي');
INSERT INTO `countries` VALUES (null,'MZ', 'Mozambique','موزمبيق','Mozambican','موزمبيقي');
INSERT INTO `countries` VALUES (null,'MM', 'Myanmar','ميانمار','Myanmarian','ميانماري');
INSERT INTO `countries` VALUES (null,'NA', 'Namibia','ناميبيا','Namibian','ناميبي');
INSERT INTO `countries` VALUES (null,'NR', 'Nauru','نورو','Nauruan','نوري');
INSERT INTO `countries` VALUES (null,'NP', 'Nepal','نيبال','Nepalese','نيبالي');
INSERT INTO `countries` VALUES (null,'NL', 'Netherlands','هولندا','Dutch','هولندي');
INSERT INTO `countries` VALUES (null,'AN', 'Netherlands Antilles','جزر الأنتيل الهولندي','Dutch Antilier','هولندي');
INSERT INTO `countries` VALUES (null,'NC', 'New Caledonia','كاليدونيا الجديدة','New Caledonian','كاليدوني');
INSERT INTO `countries` VALUES (null,'NZ', 'New Zealand','نيوزيلندا','New Zealander','نيوزيلندي');
INSERT INTO `countries` VALUES (null,'NI', 'Nicaragua','نيكاراجوا','Nicaraguan','نيكاراجوي');
INSERT INTO `countries` VALUES (null,'NE', 'Niger','النيجر','Nigerien','نيجيري');
INSERT INTO `countries` VALUES (null,'NG', 'Nigeria','نيجيريا','Nigerian','نيجيري');
INSERT INTO `countries` VALUES (null,'NU', 'Niue','ني','Niuean','ني');
INSERT INTO `countries` VALUES (null,'NF', 'Norfolk Island','جزيرة نورفولك','Norfolk Islander','نورفوليكي');
INSERT INTO `countries` VALUES (null,'MP', 'Northern Mariana Islands','جزر ماريانا الشمالية','Northern Marianan','ماريني');
INSERT INTO `countries` VALUES (null,'NO', 'Norway','النرويج','Norwegian','نرويجي');
INSERT INTO `countries` VALUES (null,'OM', 'Oman','عمان','Omani','عماني');
INSERT INTO `countries` VALUES (null,'PK', 'Pakistan','باكستان','Pakistani','باكستاني');
INSERT INTO `countries` VALUES (null,'PW', 'Palau','بالاو','Palauan','بالاوي');
INSERT INTO `countries` VALUES (null,'PS', 'Palestine','فلسطين','Palestinian','فلسطيني');
INSERT INTO `countries` VALUES (null,'PA', 'Panama','بنما','Panamanian','بنمي');
INSERT INTO `countries` VALUES (null,'PG', 'Papua New Guinea','بابوا غينيا الجديدة','Papua New Guinean','بابوي');
INSERT INTO `countries` VALUES (null,'PY', 'Paraguay','باراغواي','Paraguayan','بارغاوي');
INSERT INTO `countries` VALUES (null,'PE', 'Peru','بيرو','Peruvian','بيري');
INSERT INTO `countries` VALUES (null,'PH', 'Philippines','الفليبين','Filipino','فلبيني');
INSERT INTO `countries` VALUES (null,'PN', 'Pitcairn','بيتكيرن','Pitcairn Islander','بيتكيرني');
INSERT INTO `countries` VALUES (null,'PL', 'Poland','بولونيا','Polish','بوليني');
INSERT INTO `countries` VALUES (null,'PT', 'Portugal','البرتغال','Portuguese','برتغالي');
INSERT INTO `countries` VALUES (null,'PR', 'Puerto Rico','بورتو ريكو','Puerto Rican','بورتي');
INSERT INTO `countries` VALUES (null,'QA', 'Qatar','قطر','Qatari','قطري');
INSERT INTO `countries` VALUES (null,'RE', 'Reunion Island','ريونيون','Reunionese','ريونيوني');
INSERT INTO `countries` VALUES (null,'RO', 'Romania','رومانيا','Romanian','روماني');
INSERT INTO `countries` VALUES (null,'RU', 'Russian','روسيا','Russian','روسي');
INSERT INTO `countries` VALUES (null,'RW', 'Rwanda','رواندا','Rwandan','رواندا');
INSERT INTO `countries` VALUES (null,'KN', 'Saint Kitts and Nevis','سانت كيتس ونيفس,','Kittitian/Nevisian','سانت كيتس ونيفس');
INSERT INTO `countries` VALUES (null,'MF', 'Saint Martin (French part)','ساينت مارتن فرنسي','St. Martian(French)','ساينت مارتني فرنسي');
INSERT INTO `countries` VALUES (null,'SX', 'Sint Maarten (Dutch part)','ساينت مارتن هولندي','St. Martian(Dutch)','ساينت مارتني هولندي');
INSERT INTO `countries` VALUES (null,'LC', 'Saint Pierre and Miquelon','سان بيير وميكلون','St. Pierre and Miquelon','سان بيير وميكلوني');
INSERT INTO `countries` VALUES (null,'VC', 'Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين','Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين');
INSERT INTO `countries` VALUES (null,'WS', 'Samoa','ساموا','Samoan','ساموي');
INSERT INTO `countries` VALUES (null,'SM', 'San Marino','سان مارينو','Sammarinese','ماريني');
INSERT INTO `countries` VALUES (null,'ST', 'Sao Tome and Principe','ساو تومي وبرينسيبي','Sao Tomean','ساو تومي وبرينسيبي');
INSERT INTO `countries` VALUES (null,'SA', 'Saudi Arabia','المملكة العربية السعودية','Saudi Arabian','سعودي');
INSERT INTO `countries` VALUES (null,'SN', 'Senegal','السنغال','Senegalese','سنغالي');
INSERT INTO `countries` VALUES (null,'RS', 'Serbia','صربيا','Serbian','صربي');
INSERT INTO `countries` VALUES (null,'SC', 'Seychelles','سيشيل','Seychellois','سيشيلي');
INSERT INTO `countries` VALUES (null,'SL', 'Sierra Leone','سيراليون','Sierra Leonean','سيراليوني');
INSERT INTO `countries` VALUES (null,'SG', 'Singapore','سنغافورة','Singaporean','سنغافوري');
INSERT INTO `countries` VALUES (null,'SK', 'Slovakia','سلوفاكيا','Slovak','سولفاكي');
INSERT INTO `countries` VALUES (null,'SI', 'Slovenia','سلوفينيا','Slovenian','سولفيني');
INSERT INTO `countries` VALUES (null,'SB', 'Solomon Islands','جزر سليمان','Solomon Island','جزر سليمان');
INSERT INTO `countries` VALUES (null,'SO', 'Somalia','الصومال','Somali','صومالي');
INSERT INTO `countries` VALUES (null,'ZA', 'South Africa','جنوب أفريقيا','South African','أفريقي');
INSERT INTO `countries` VALUES (null,'GS', 'South Georgia and the South Sandwich','المنطقة القطبية الجنوبية','South Georgia and the South Sandwich','لمنطقة القطبية الجنوبية');
INSERT INTO `countries` VALUES (null,'SS', 'South Sudan','السودان الجنوبي','South Sudanese','سوادني جنوبي');
INSERT INTO `countries` VALUES (null,'ES', 'Spain','إسبانيا','Spanish','إسباني');
INSERT INTO `countries` VALUES (null,'SH', 'Saint Helena','سانت هيلانة','St. Helenian','هيلاني');
INSERT INTO `countries` VALUES (null,'SD', 'Sudan','السودان','Sudanese','سوداني');
INSERT INTO `countries` VALUES (null,'SR', 'Suriname','سورينام','Surinamese','سورينامي');
INSERT INTO `countries` VALUES (null,'SJ', 'Svalbard and Jan Mayen','سفالبارد ويان ماين','Svalbardian/Jan Mayenian','سفالبارد ويان ماين');
INSERT INTO `countries` VALUES (null,'SZ', 'Swaziland','سوازيلند','Swazi','سوازيلندي');
INSERT INTO `countries` VALUES (null,'SE', 'Sweden','السويد','Swedish','سويدي');
INSERT INTO `countries` VALUES (null,'CH', 'Switzerland','سويسرا','Swiss','سويسري');
INSERT INTO `countries` VALUES (null,'SY', 'Syria','سوريا','Syrian','سوري');
INSERT INTO `countries` VALUES (null,'TW', 'Taiwan','تايوان','Taiwanese','تايواني');
INSERT INTO `countries` VALUES (null,'TJ', 'Tajikistan','طاجيكستان','Tajikistani','طاجيكستاني');
INSERT INTO `countries` VALUES (null,'TZ', 'Tanzania','تنزانيا','Tanzanian','تنزانيي');
INSERT INTO `countries` VALUES (null,'TH', 'Thailand','تايلندا','Thai','تايلندي');
INSERT INTO `countries` VALUES (null,'TL', 'Timor-Leste','تيمور الشرقية','Timor-Lestian','تيموري');
INSERT INTO `countries` VALUES (null,'TG', 'Togo','توغو','Togolese','توغي');
INSERT INTO `countries` VALUES (null,'TK', 'Tokelau','توكيلاو','Tokelaian','توكيلاوي');
INSERT INTO `countries` VALUES (null,'TO', 'Tonga','تونغا','Tongan','تونغي');
INSERT INTO `countries` VALUES (null,'TT', 'Trinidad and Tobago','ترينيداد وتوباغو','Trinidadian/Tobagonian','ترينيداد وتوباغو');
INSERT INTO `countries` VALUES (null,'TN', 'Tunisia','تونس','Tunisian','تونسي');
INSERT INTO `countries` VALUES (null,'TR', 'Turkey','تركيا','Turkish','تركي');
INSERT INTO `countries` VALUES (null,'TM', 'Turkmenistan','تركمانستان','Turkmen','تركمانستاني');
INSERT INTO `countries` VALUES (null,'TC', 'Turks and Caicos Islands','جزر توركس وكايكوس','Turks and Caicos Islands','جزر توركس وكايكوس');
INSERT INTO `countries` VALUES (null,'TV', 'Tuvalu','توفالو','Tuvaluan','توفالي');
INSERT INTO `countries` VALUES (null,'UG', 'Uganda','أوغندا','Ugandan','أوغندي');
INSERT INTO `countries` VALUES (null,'UA', 'Ukraine','أوكرانيا','Ukrainian','أوكراني');
INSERT INTO `countries` VALUES (null,'AE', 'United Arab Emirates','الإمارات العربية المتحدة','Emirati','إماراتي');
INSERT INTO `countries` VALUES (null,'GB', 'United Kingdom','المملكة المتحدة','British','بريطاني');
INSERT INTO `countries` VALUES (null,'US', 'United States','الولايات المتحدة','American','أمريكي');
INSERT INTO `countries` VALUES (null,'UM', 'US Minor Outlying Islands','قائمة الولايات والمناطق الأمريكية','US Minor Outlying Islander','أمريكي');
INSERT INTO `countries` VALUES (null,'UY', 'Uruguay','أورغواي','Uruguayan','أورغواي');
INSERT INTO `countries` VALUES (null,'UZ', 'Uzbekistan','أوزباكستان','Uzbek','أوزباكستاني');
INSERT INTO `countries` VALUES (null,'VU', 'Vanuatu','فانواتو','Vanuatuan','فانواتي');
INSERT INTO `countries` VALUES (null,'VE', 'Venezuela','فنزويلا','Venezuelan','فنزويلي');
INSERT INTO `countries` VALUES (null,'VN', 'Vietnam','فيتنام','Vietnamese','فيتنامي');
INSERT INTO `countries` VALUES (null,'VI', 'Virgin Islands (U.S.)','الجزر العذراء الأمريكي','American Virgin Islander','أمريكي');
INSERT INTO `countries` VALUES (null,'VA', 'Vatican City','فنزويلا','Vatican','فاتيكاني');
INSERT INTO `countries` VALUES (null,'WF', 'Wallis and Futuna Islands','والس وفوتونا','Wallisian/Futunan','فوتوني');
INSERT INTO `countries` VALUES (null,'EH', 'Western Sahara','الصحراء الغربية','Sahrawian','صحراوي');
INSERT INTO `countries` VALUES (null,'YE', 'Yemen','اليمن','Yemeni','يمني');
INSERT INTO `countries` VALUES (null,'ZM', 'Zambia','زامبيا','Zambian','زامبياني');
INSERT INTO `countries` VALUES (null,'ZW', 'Zimbabwe','زمبابوي','Zimbabwean','زمبابوي');
